name: iOS Build & TestFlight Upload

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 3 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Debug Repository Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repo:"
          ls -R

      # Auto-increment build number
      - name: Increment Build Number
        run: |
          plist="XsiteBroker/Info.plist"
          buildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$plist" 2>/dev/null || echo 0)
          newBuildNumber=$((buildNumber + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $newBuildNumber" "$plist" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $newBuildNumber" "$plist"
          echo "✅ Updated build number to $newBuildNumber"

      # Validate Info.plist
      - name: Validate Info.plist
        run: |
          plist="XsiteBroker/Info.plist"
          echo "🔍 Validating Info.plist..."
          if [ ! -f "$plist" ]; then
            echo "❌ Info.plist missing at $plist"; exit 1
          fi
          if ! grep -q "<key>CFBundleIdentifier</key>" "$plist"; then
            echo "❌ Missing CFBundleIdentifier in Info.plist"; exit 1
          fi
          echo "✅ Info.plist validated successfully"

      # Resolve Swift Packages
      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies \
          -project "XsiteBroker/XsiteBroker.xcodeproj"

      # Build for Simulator (for testing)
      - name: Build for Simulator
        run: xcodebuild clean build \
          -project "XsiteBroker/XsiteBroker.xcodeproj" \
          -scheme "XsiteBroker" \
          -destination 'platform=iOS Simulator,name=iPhone 17 Pro'

      # Archive the app
      - name: Archive for Release
        run: xcodebuild \
          -project "XsiteBroker/XsiteBroker.xcodeproj" \
          -scheme "XsiteBroker" \
          -archivePath build/XsiteBroker.xcarchive archive

      # Export IPA
      - name: Export IPA
        run: xcodebuild -exportArchive \
          -archivePath build/XsiteBroker.xcarchive \
          -exportPath build/ipa \
          -exportOptionsPlist ExportOptions.plist

      # Upload to TestFlight
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ipa/XsiteBroker.ipa
          issuer-id: ${{ 964974c3-189c-4839-aeff-713d9428c5c5 }}
          api-key-id: ${{ UWSRAN8L72 }}
          api-private-key: ${{ -----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg5Hcy/2KofeTH4m5v
Xix0JThoP2iD7bvp3sVb9eF+qhWgCgYIKoZIzj0DAQehRANCAAT83+OENlCKXVxu
ECgU4Zm46xqjXhfIWfEteDnbH3dSWDNjU4MisbNALJPD99R3pxjt6MMFGeSB27GV
1JLbpMbw
-----END PRIVATE KEY----- }}

      - name: Cleanup Build Files
        if: always()
        run: |
          rm -rf build
          echo "🧹 Cleaned build artifacts"
